Backup refactor (#51)
* starting major refactor of backup.awk

* cleanup of zelta-backup.awk and refactored zelta-args.awk to data-driven approach

* imrpoved zelta-args.awk and data-driven to Zelta Match properties

* continuing work on arg processing, small bugfixes in 'zelta', 'zelta-common.awk', and 'zelta-args.awk'

* continuing work on arg processing, small bugfixes in 'zelta', 'zelta-common.awk', and 'zelta-args.awk'

* continuing work on arg processing, small bugfixes in 'zelta', 'zelta-common.awk', and 'zelta-args.awk'

* continuing work on arg processing, small bugfixes in 'zelta', 'zelta-common.awk', and 'zelta-args.awk'

* sub-option tuneup

* endpoint and option exception cleanup, rename PREFIX to [ENDPOINT]_REMOTE

* refactor backup, change perms to no execute (they're no longer standalone scripts), starting to trim out logic-overloaded code

* accidentally duplicated a bunch of stuff; committed this so I don't lose anything

* fixed accidental cody copy; improved zfs send command builder

* added suffix to command builder, improved sync planning logic, fixed some basic sync patterns

* removed comments, renamed sync loop function to run_zfs_sync()

* comments and comment cleanup

* slightly jenky data driven summary output for json

* removed PROP_CHECK option (unsafe due to encryption likelihood); tried to make variable names clearer; removed messages from action step; cleaned up compute_snapshot_paths and compute_sync_action; aligned output with zelta 1.0 json; restructured planning function so we can rerun 'zelta match' easily after a sync pass

* better remote handling for spaces in dataset names, 2-step full replications, better sync handling

* 'zelta clone'

* 'zelta rotate target origin mode'

* separated snapshot validation logic; experimented with streamlining sync and clone; added snap modes to clone

* fixed blocking logic; fixed rotate target mode

* auto-resume

* added clone-in-place

* renamed clone-in-place command to 'zelta revert', added command and usage

* 'zelta rotate' source divergence mode restored and improved

* 'zelta rotate' source divergence mode restored and improved (logic/bug fixes)

* tracking bug for zelta rever/rotate

* minor run_zfs_sync() visual tweak, generalized rename_target to rename_dataset(), and create_recursive_clone(), cleaned up run_revert(), command tweaks, and check_origin_match() minor bug fix

---------

Co-authored-by: Daniel J. Bell <daniel@belltower.it>

diff --git a/bin/zelta b/bin/zelta
--- a/bin/zelta
+++ b/bin/zelta
@@ -54,11 +54,12 @@ zelta_man() {
 
 
 zelta_init() {
-
-
 	AWK="${ZELTA_AWK:-${AWK:-awk}}"
+	ZELTA_VERB="${zelta_verb}"
+
 	: ${ZELTA_ETC:="/usr/local/etc/zelta"}	# Dir for the default env and policy
 	: ${ZELTA_ENV:="$ZELTA_ETC/zelta.env"}	# Edit this file to change command defaults
+
 	
 	# Read zelta.env prepending ZELTA_ prefix when necessary
 	if [ -r "$ZELTA_ENV" ]; then
@@ -76,47 +77,61 @@ zelta_init() {
 		eval "$_env_settings"
 	fi
 
+	# Verb-specific defaults
+	case "$zelta_verb" in
+		clone)	: ${ZELTA_SEND_INTR:="0"}
+			;;
+		rotate)	: ${ZELTA_SEND_INTR:="0"}
+			;;
+		sync)	: ${ZELTA_SEND_INTR:="0"}
+			;;
+	esac
+
 	: ${ZELTA_SHARE:="/usr/local/share/zelta"}	# Dir for helper scripts
 	: ${ZELTA_CONFIG:="$ZELTA_ETC/zelta.conf"}	# YAML for "zelta policy"
 
 	# Zelta defaults:
+	: ${ZELTA_LOG_LEVEL:="2"}
 	: ${ZELTA_LOG_COMMAND:="zelta ipc-log"}
 	: ${ZELTA_TIME_COMMAND:="time -p"}
 	: ${ZELTA_SH_COMMAND_PREFIX:="{"}
 	: ${ZELTA_SH_COMMAND_SUFFIX:="; }"}
-	: ${ZELTA_SNAP_NAME:="date -u +%Y-%m-%d_%H.%M.%S"}
-	: ${ZELTA_SNAP_MODE:="IF_NONE"}
+	: ${ZELTA_SNAP_COMMAND:="date -u +%Y-%m-%d_%H.%M.%S"}
+	: ${ZELTA_SNAP_NAME:="$($ZELTA_SNAP_COMMAND)"}
+	: ${ZELTA_SNAP_MODE:="IF_NEEDED"}
+	: ${ZELTA_SYNC_DIRECTION:="PULL"}
+	: ${ZELTA_CHECK_TIME:=""}
 
-	: ${ZELTA_SEND_DEFAULT:="-Lec"}
-	: ${ZELTA_SEND_RAW:="-Lw"}
+	# `zfs list` defaults
+	: ${ZELTA_LIST_WRITTEN:="1"}
+
+	# Safety options
+	: ${ZELTA_CREATE_PARENT:="1"}
+	: ${ZELTA_RESUME:="1"}
+
+	# `zfs send` defaults
+	: ${ZELTA_SEND_DEFAULT:="-L -c -e"}
+	: ${ZELTA_SEND_RAW:="-L -w"}
 	: ${ZELTA_SEND_NEW:="-p"}
-	: ${ZELTA_SEND_INTR:="-i"}
-	: ${ZELTA_SEND_PARTIAL:="-t"}
-	: ${ZELTA_SEND_REPLICATE:="-Rs"}
+	: ${ZELTA_SEND_INTR:="1"}
+	: ${ZELTA_SEND_PARTIAL:="1"}
+	: ${ZELTA_SEND_REPLICATE:="-L -s -R -w"}
 
-	: ${ZELTA_SEND_CHECK:="no"}
-
+	# `zfs recv` defaults
 	: ${ZELTA_RECV_DEFAULT:=""}
 	: ${ZELTA_RECV_TOP:="-o readonly=on"}
-	: ${ZELTA_RECV_FS:="-u -x mountpoint"}
+	: ${ZELTA_RECV_FS:="-u -x mountpoint -o canmount=noauto"}
 	: ${ZELTA_RECV_VOL:=""}
 	: ${ZELTA_RECV_PARTIAL:="-s"}
 
-	: ${ZELTA_RESUME:="yes"}
-
+	# `zfs clone` defaults
 	: ${ZELTA_CLONE_DEFAULT:="-po readonly=off"}
 
+	# Remote (ssh) options
 	: ${ZELTA_REMOTE_COMMAND:="ssh"}
 	: ${ZELTA_REMOTE_DEFAULT:="${ZELTA_REMOTE_COMMAND} -n"}
 	: ${ZELTA_REMOTE_SEND:="${ZELTA_REMOTE_DEFAULT}"}
 	: ${ZELTA_REMOTE_RECV:="${ZELTA_REMOTE_COMMAND}"}
-
-	: ${ZELTA_LOG_LEVEL:="2"}
-
-	ZELTA_VERB="${zelta_verb}"
-
-	# We're prioritizing ZELTA_AWK over AWK (but use AWK below for clarity)
-	AWK="${ZELTA_AWK:-${AWK:-awk}}"
 
 	export AWK $(set | $AWK -F= '/^ZELTA_.*=/{print $1}')
 }
@@ -130,17 +145,36 @@ zelta_run_awk() {
 
 zelta_args() {
 	if [ -n "$1" ]; then
-		_opts=$(zelta_run_awk "args" "$@")
-		eval export "$_opts"
+		if _opts=$(zelta_run_awk "args" "$@") ; then
+			[ -n "$_opts" ] && eval export "$_opts"
+		else
+			export ZELTA_USAGE="1"
+		fi
 	fi
 }
 
 zelta_log() {
 	: ${max_log_level:=${ZELTA_LOG_LEVEL:-2}}
+	# Bourne handles stderr/stdout reporting more reliably and portably than some awks, so
+	# this function is used for the default LOG_MODE. STDERR messages are retained even when
+	# selecting another, like LOG_MODE=json. To disable STDERR noise, use `zelta VERB -qq ...`
+	_fd=3
+	_fd_term=4
+	if [ -n "$ZELTA_LOG_FILE" ] ; then
+		#_fd=" >> '${ZELTA_LOG_FILE}'"
+		exec 3>>"$ZELTA_LOG_FILE"
+		exec 4>&3
+	else
+		exec 3>&2
+		exec 4>&1
+		if [ "${ZELTA_LOG_MODE:-text}" = "text" ]; then
+			_term="1"
+		fi
+	fi
 	while IFS="	" read log_level log_message; do
 		: ${log_level:=${log_level:-2}}
 		# If no log_level is given, treat it as a "notice"
-		case $log_level in
+		case "$log_level" in
 		*[!0-9]*)	log_message="${log_level}${log_message:+ }${log_message}"
 				log_level=2
 				;;
@@ -149,24 +183,21 @@ zelta_log() {
 		if [ "$log_level" -gt "$max_log_level" ] ; then
 			# Log level hasn't been met, skip
 			continue
-		elif [ "$log_level" -lt "0" ] ; then
-			# Force log output if log_level < 1
-			echo "critical: ${log_message}" >&2 
-		elif [ -t 2 ] && [ "$log_level" = 2 ] ; then
+		elif [ -n "$_term" ] && [ "$log_level" = 2 ] ; then
 			# "Notice" is regular stdout on a term
-			echo $log_message
-		elif [ -t 2 ] && [ "$log_level" = 3 ] ; then
+			echo $log_message >&${_fd_term}
+		elif [ -n "$_term" ] && [ "$log_level" = 3 ] ; then
 			# "Info" is regular stderr on a term
-			echo $log_message >&2
+			echo $log_message >&${_fd}
 		else
 			case "$log_level" in
-			0)	log_prefix="error: " ;;
 			1)	log_prefix="warning: " ;;
 			2)	log_prefix="notice: " ;;
 			3)	log_prefix="info: " ;;
-			*)	log_prefix="debug: " ;;
+			4)	log_prefix="debug: " ;;
+			*)	log_prefix="error: " ;;
 			esac
-			echo "${log_prefix}${log_message}" >&2 
+			echo "${log_prefix}${log_message}" >&${_fd}
 		fi
 	done
 	exit
@@ -190,6 +221,7 @@ ipc-log)	shift;
 		;;
 ipc-run)
 		# For internal calls. Environment is pre-set.
+		export ZELTA_VERB="$1"
 		zelta_verb="$1"
 		shift
 		;;
@@ -210,6 +242,8 @@ case $zelta_verb in
 	# zelta-backup.awk
 	clone |\
 	replicate |\
+	revert |\
+	rotate |\
 	sync |\
 	zpull |\
 	zpush |\
@@ -218,8 +252,8 @@ case $zelta_verb in
 	policy)		zelta_run_awk "policy" ;;
 	# Utilities
 	zeport)		zelta_run_awk "report" ;;
-	# Workaround for Linux with no /bin/sh "time -p" and no /usr/bin/time
-	time)		"$@" | bash -c "time -p cat" ;;
+	# Time
+	time)		"$@" | sh -c "time -p cat" ;;
 	# Info
 	-V |\
 	--version |\
